include::topics/shared/attributes.adoc[]

//':chapter:' is a vital parameter. See: http://asciidoctor.org/docs/user-manual/#include-multiple
:chapter: introducing-raincatcher-security-features

//Concepts
= Introducing {WFM-RC-NameShort} Security Features

{WFM-RC-NameShort} Security is built around a *Security Interface* which abstracts itself from all {WFM-RC-NameShort} security libraries.
{WFM-RC-NameShort} allows you to build a custom security solution for integration with {WFM-RC-NameShort}.
{WFM-RC-NameShort} also provides two security implementations out-of-the-box and are called link:http://www.keycloak.org/[Keycloak] and link:http://passportjs.org/[Passport.js].

*Keycloak* and *Passport.js* both provide authentication and authorization on the server side.
*Keycloak* and *Passport.js* implementations can replace each other without breaking the internal api belonging to all {WFM-RC-NameShort} module's and also any of the reference applications.

== Authorization using the Security Interface
If you build a custom security implementation, the endpoints are secured in the same way as the *Keycloak* and *Passport.js* implementations.

If you choose to build a custom security implementation, you will need to:

 . Import the link:++../../../api/{WFM-RC-Api-Version}/auth-passport/docs/interfaces/_src_auth_passportauth_.endpointsecurity.html++[EndpointSecurity] interface from Passport.js
 . Implement the interface in the custom security implementation
 . Use the _protect_ method to guard routes (the security permissions being role based)

NOTE: All link:https://expressjs.com/[express] routes outside of WFM modules must implement the link:++../../../api/{WFM-RC-Api-Version}/auth-passport/docs/interfaces/_src_auth_passportauth_.endpointsecurity.html++[EndpointSecurity] Security Interface.

//Pasport.js
include::topics/con-passportjs-module.adoc[leveloffset=+1]

The security aspects of *Passport.js* module are described in the Security Strategy and cover areas such as:

* Understanding Session Management
* Defining Access Control
* Defining Password Storage
* Passport.js Authentication
* Passport.js Authorization

For more information on the *Passport.js* Security Strategy, see xref:ref-passportjs-securitystrategy-defining-raincatcher-security[Defining the Security Strategy for {WFM-RC-NameShort} Passport.js]

== Introducing the {WFM-RC-NameShort} Keycloak Module
The *Keycloak* module is a complete identity management solution that extends standard authorization and authentication functionality and comes with all the overheads involved in running a server.
Red Hat recommends using *Keycloak* in production to avail of the many features available for enterprise security including:

* link:https://keycloak.gitbooks.io/documentation/server_admin/topics/sso-protocols.html[Single-Sign On]
* link:https://keycloak.gitbooks.io/documentation/content/server_admin/topics/user-federation.html[User Federation]
* link:https://keycloak.gitbooks.io/documentation/content/server_admin/topics/authentication/x509.html[Client Cert Authentication]
* link:https://keycloak.gitbooks.io/documentation/content/server_admin/topics/authentication/otp-policies.html[2FA with OTP]
* link:https://keycloak.gitbooks.io/documentation/content/server_admin/topics/sessions/administering.html[User Session Management]
* link:https://keycloak.gitbooks.io/documentation/server_admin/topics/events.html[Auditing]
* link:https://keycloak.gitbooks.io/documentation/content/server_admin/topics/threat/brute-force.html[Brute Force Detection]

NOTE: *Keycloak* is _not_ available by default when running the default {WFM-RC-NameShort} solution

== Choosing Passport.js or Keycloak
*Passport.js*:

* If you want a standalone Node.js based authentication solution that is ready out-of-the-box, choose *Passport.js*

*Keycloak*:

* If you want a full identity management solution that can be tied into existing saml/ldap/sso solutions, choose *Keycloak*.
