include::topics/shared/attributes.adoc[]

//':context:' is a vital parameter. See: http://asciidoctor.org/docs/user-manual/#include-multiple
:context: running-the-published-repositories

= Running the {PROJECT_NAME} Applications on a Local Machine

= Running the Published Repositories for the Demo App
//Concepts
The *{PROJECT_NAME}* {PROJECT_NAME} Apps from the _Published Repositories_ comprise of three applications:

* _Mobile_
* _Portal_
* _Node.js Server_

These applications are also available in standalone repositories that point to published versions of the {PROJECT_NAME} packages.
Running the demo applications as described in this section provides a simpler and more stable alternative to users that only wish to test them locally on their machines,
without the extra concerns required only for a development setup.

// Procedure
include::topics/pro-running-the-demo-repositories.adoc[leveloffset=+1]
For login details, refer to the xref:{context}-credentials-for-the-mobile-and-portal-application[Credentials for the Mobile and Portal Application] section of xref:{context}-ref-demo-app[{PROJECT_NAME} Application Reference Material].

// Related Information
include::topics/ref-demo-app.adoc[leveloffset=+1]
