[]
= Introduction to {WFM-RC-NameShort} security features

{WFM-RC-NameShort} server gives developers a choice one of the following authentication and authorisation providers
link:http://www.keycloak.org/[Keycloak] and link:http://passportjs.org/[Passport.js].
{WFM-RC-NameShort} is build around security interface, which abstracts from any security libraries.
Both implementations can be swapped at any time without breaking internal api of {WFM-RC-NameShort} modules and reference applications.
Users can also provide their own security implementation by implementing their own security interface.s

Another security measures are incorporated into our reference applications.
Please note that all link:https://expressjs.com/[express] based routes outside WFM modules will also need to use these security interfaces.

== How to apply authorization using security interface
You can choose Keycloak or Passport.js implementation but you can securing endpoints in the same way.
You need to import link:++../../../api/{WFM-RC-Api-Version}/auth-passport/docs/interfaces/_src_auth_passportauth_.endpointsecurity.html++[EndpointSecurity]
interface from passportAuth. Apply either implementation initialisation to the interface.
You can then use this security interface protect method to guard routes with roles.

== Passport.js
Passport.js is a lightweight authentication middleware for Node.js that is extremely flexible and modular.
Passport.js offers comprehensive set of link:http://passportjs.org/docs/configure[strategies] that support authentication
using a username and password, Facebook, Twitter, and more.
For more information see link:http://passportjs.org/[passport.org].

- Can be bundled into existing node.js server
- Available by default when running our reference server application
- Covers authentication and authorization of express routes

== Keycloak
Keycloak is a full identity management solution with features that extend standard authorization and authentication scope.
Keycloak will be suggested for solutions that require more comprehensive integration with company infrastructure and
work as identify management solution

For a full feature list, see link:https://keycloak.gitbooks.io/documentation/server_admin/topics/overview/features.html[Keycloak]

== Which to use?

Both solutions have their benefits

*Keycloak*

If you are looking for a full identity management solution that can be tied into
existing *saml/ldap/sso* solutions then Keycloak should be your choice. Keycloak is an separate
identity management server with all the overheads involved in running a server.

*Passport.js*

If you are looking for a standalone Node.js based authentication solution that is ready out of the box then passport.js
should be your choice.
