[id='{context}-con-introducing-raincatcher']
ifdef::downstream[]
= Introducing Workforce Management

Workforce Management is a Workforce Management Platform and is also referred to as {Feature}.
endif::downstream[]

ifdef::upstream[]
= Introducing {Feature}

{Feature} is a Workforce Management Platform.
endif::upstream[]

The latest version of {Feature} is {WFM-RC-Version}.

{Feature} connects a business’ back-office with its fleet of mobilized employees.
{Feature} leverages commoditized mobile hardware, making use of each employee’s mobile phone.

The primary goal of {Feature} is to ease mobile enablement efforts.
It achieves that by providing set of modules that can be integrated into existing applications additionally
{Feature} allows developers to leverage existing demo-solution by extending it to suit their business needs.

Main features in the latest {WFM-RC-Version}:

* Workflow Management
* Real-time Data Access
* Data Synchronization

Roadmap:

* Plugable authentication
* Image capture
* Geolocation
* Internal Messaging and 3rd party Messaging
* Mobile Forms
* Real-time Data Access
* Integration of sensor data

{Feature} {WFM-RC-Version} features:

* Security
* Logging
* Data Synchronization
