[id='con-datasync-module-{chapter}']
= Introducing the {WFM-RC-NameShort} Datasync Module

The *Datasync* Module is an implementation of the {WFM-RC-NameShort} Sync Framework.
*Datasync* is made up of two applicaitons, the xref:datasync-cloud-app-{chapter}[Cloud App] and the xref:datasync-client-app-{chapter}[Client App].
The Cloud App is implemented in the *Datasync* cloud module and the Client App is implemented in the *Datasync* client module. 
The primary function of *Datasync* is to synchronize data between the Client Apps (mobile) and the Cloud App running on a backend server.

*Datasync* key features:

- Allows synchronization of the {WFM-RC-NameShort} workorder data between the {WFM-RC-NameShort} Client Apps (mobile) and the {WFM-RC-NameLong} Cloud App running on a backend server
- Allows Client Apps (mobile) to use and update data offline (local cache)
- Provides a mechanism to manage bi-directional data synchronization from multiple Client Apps into back-end data stores via the Cloud App
- Allows data updates (that is, deltas) to be distributed from the Cloud App to connected clients
- Provides facilities for managing data collisions from multiple updates in the cloud

For advanced usage of the *Datasync* Module, see the link:{WFM-RC-SyncFrameworkURL}{WFM-RC-Branch}/docs[sync framework documentation]. 

[id='datasync-cloud-app-{chapter}']
== Datasync Cloud App
The *Datasync Cloud App* is a wrapper for the {WFM-RC-NameShort} link:https://github.com/feedhenry/fh-sync[Datasync server].
The *Datasync Cloud App* creates a server side service that allows Client Apps (mobile) to synchronize offline data to a preferred back-end data store.
By default, the server connects to a backend mongodb database and stores all client data here. 

For instructions on how to implement the *Datasync Cloud App*, see the *Datasync Cloud App* link:{WFM-RC-CoreURL}{WFM-RC-Branch}/cloud/datasync/README.md[README.MD]

To view an exmaple, see the *Datasync Cloud App* link:{WFM-RC-CoreUrl}{WFM-RC-Branch}/cloud/datasync/example/index.ts[example].

[id='datasync-client-app-{chapter}']
== Datasync Client App
The *Datasync Client App* is based on the link:https://github.com/feedhenry/fh-sync-js[sync.js client].
In order to work, the *Datasync Client App* requres the *Datasync Cloud App* to be running on an _Express_ web server.
The _Data Synchonization Library_ can be used for offline storage of mobile applications data.

For instructions on how to implement the *Datasync Client App*, see the *Datasync Client App* link:{WFM-RC-CoreURL}{WFM-RC-Branch}/client/datasync-client/README.md[README.MD]

To view an exmaple, see the *Datasync Client App* link:{WFM-RC-CoreUrl}{WFM-RC-Branch}/cloud/datasync/example/index.ts[example].
