[id='{context}-pro-keycloak-enablement']
= Enabling {Keycloak}

The xref:{context}-adding-keycloak-configuration[Adding {Keycloak} Configuration] and xref:{context}-enabling-keycloak-on-the-demo-server[Enabling {Keycloak} on the Demo Server] headings below are valid for any instance of *{Keycloak}* provided you implement the _Realm settings_.

IMPORTANT: Enabling *{Keycloak}* requires the disabling of *PassportAuth*.

[discrete]
== Prerequisites

. Ensure you have completed xref:getting-started[Getting Started]
. Docker (tested with version: {WFM-RC-DockerVersion})

[id='{context}-run-keycloak-docker-image']
[discrete]
== Running the {Keycloak} Docker Image

. Open a terminal and run the *{Keycloak}* Docker image

[source,bash]
----
docker run -p 8080:8080 feedhenry/raincatcher-keycloak
----

For more information about the *{Keycloak}* Docker Image, see the *{Keycloak}* link:{WFM-RC-KeycloakDockerURL}{WFM-RC-Branch}/README.md[README.md].

[id={context}-adding-keycloak-configuration]
[discrete]
== Adding {Keycloak} Configuration

. Choose which _configuration file_ to edit:
+
.*{Keycloak}* Configuration File
|===
|Area |File Name | File Location

|Development
|link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/config-dev.json[config-dev.json]
|/demo/server/config-dev.json

|Production
|link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/config-prod.json[config-prod.json]
|/demo/server/config-prod.json

|===
+
NOTE: The `keycloakConfig` field is partially implemented in link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/config-prod.json[config-prod.json].
+
. Open the _configuration file_, create a new field called `keycloakConfig` and add the following data to `keycloakConfig`:
+
[source,javascript]
----
"keycloakConfig":{
                    "realm": "raincatcher",
                    "bearer-only": true,
                    "auth-server-url": "http://localhost:8080/auth",
                    "ssl-required": "external",
                    "resource": "raincatcher-cloud",
                    "use-resource-role-mappings": true
                  }
----


[id={context}-enabling-keycloak-on-the-demo-server]
[discrete]
== Enabling {Keycloak} on the Demo Server

. Open the file link:{WFM-RC-AngularJsURL}{WFM-RC-Branch}/demo/mobile/src/app/app.js[app.js] in location _/demo/mobile/src/app/_ and change the contents to:
+
[source,javascript]
----
    // Comment to disable passport auth
    require('@raincatcher/demo-auth-passport')('wfm-mobile'),
    // Uncomment to enable Keycloak
    // require('../keycloak');
----
+
. Open the file link:{WFM-RC-AngularJsURL}{WFM-RC-Branch}/demo/portal/src/app/main.js[main.js] in location _/demo/portal/src/app/_ and change the contents to:
+
[source,javascript]
----
    // Comment to disable passport auth
    require('@raincatcher/demo-auth-passport')('app'),
    // Uncomment to enable Keycloak
    // require('./keycloak');
----
+
. At this point, the _Routes_ are protected by *{Keycloak}*.

[id={context}-accessing-the-keycloak-admin-console]
[discrete]
== Accessing the {Keycloak} Admin Console

. To access the _{Keycloak} Admin Console_, navigate to _http://localhost:8080/auth/_
