[id='pro-running-the-demo-app-{chapter}']
= Introduction

This section includes:

. xref:pro-cloning-the-git-repository-{chapter}[Cloning the Git Repository]
. xref:pro-installing-angular-dependencies-{chapter}[Installing Angular Dependencies]
. xref:pro-installing-core-dependencies-{chapter}[Installing Core Dependencies]
. xref:pro-starting-mongodb-and-redis-{chapter}[Starting MongoDB and Redis]
. xref:pro-starting-the-core-server-{chapter}[Starting the Core Server]
. xref:pro-running-the-mobile-and-portal-demo-applications-{chapter}[Running the Mobile and Portal Demo Applications]

= Prerequisites

* Node and npm installed (tested on Node {WFM-RC-NodeVersion})
* git
* access to `git@github.com:feedhenry-raincatcher/raincatcher-angularjs.git`
* MongoDB (tested with version: {WFM-RC-MongoDBVersion})
* Redis (tested with version: {WFM-RC-RedisVersion})

= Running the Demo App

This procedure will install the latest master branch.

[id='pro-cloning-the-git-repository-{chapter}']
[discrete]
== Cloning the Git Repository

[source,bash]
----
git clone git@github.com:feedhenry-raincatcher/raincatcher-angularjs.git

cd raincatcher-angularjs
----

[id='pro-installing-angular-dependencies-{chapter}']
[discrete]
== Installing Repository Dependencies

[source,bash]
----
npm install
npm run bootstrap
----

[id='pro-installing-core-dependencies-{chapter}']
[discrete]
== Installing Core Dependencies

[source,bash]
----
cd ./core
npm install
npm run bootstrap
----

NOTE: The Core repository is automatically cloned by the command `npm run bootstrap`.

[id='pro-starting-mongodb-and-redis-{chapter}']
[discrete]
== Starting MongoDB and Redis

Start MongoDB. For more information, see link:https://docs.mongodb.com/manual/tutorial/manage-mongodb-processes/#start-mongod-processes[Start MongoDB Processes].

Start Redis. For more information, see link:https://redis.io/topics/quickstart#starting-redis[Starting Redis].

[id='pro-starting-the-core-server-{chapter}']
[discrete]
== Starting the Core Server

[source,bash]
----
npm run start
----

NOTE: The terminal is out of use while the Core Server is running. Open a new terminal to run additional commands.

[id='pro-running-the-mobile-and-portal-demo-applications-{chapter}']
[discrete]
== Running the Mobile and Portal Demo Applications

[source,bash]
----
cd ..
npm run start
----

Both the Mobile and Portal Demo open automatically in a browser.

For login details, refer to xref:credentials-for-the-demo-application-{chapter}[Credentials for the Demo Application] section of xref:ref-demo-app-{chapter}[{WFM-RC-NameShort} Demo Application Reference Material].
