[id='{context}-pro-keycloak-implementation']
= Implementing {WFM-RC-KeycloakName}

This section includes:

. xref:{context}-initializing-keycloak[Initializing {WFM-RC-KeycloakName}]
. xref:{context}-importing-the-endpointsecurity-interface[Importing the EndpointSecurity Interface]
. xref:{context}-importing-keycloak-init[Importing {WFM-RC-KeycloakName} _init_]
. xref:{context}-applying-keycloak-init[Applying {WFM-RC-KeycloakName} _init_ ]
. xref:{context}-enabling-keycloak-route-protection[Enabling {WFM-RC-KeycloakName} Route Protection]

== Prerequisites

. Ensure you have completed xref:getting-started[Getting Started]
. Docker (tested with version: {WFM-RC-DockerVersion})

== Using {WFM-RC-KeycloakName} to secure endpoints

[id='{context}-initializing-keycloak']
[discrete]
== Initializing {WFM-RC-KeycloakName}

See the link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/src/modules/keycloak/index.ts[Keycloak code] for reference.

[id='{context}-importing-the-endpointsecurity-interface']
[discrete]
== Importing The EndpointSecurity Interface

Import the link:{WFM-RC-CoreURL}{WFM-RC-Branch}/cloud/auth/src/EndpointSecurity.ts[EndpointSecurity Interface] and implement it.

[id='{context}-importing-keycloak-init']
[discrete]
== Importing {WFM-RC-KeycloakName} _init_

Import *{WFM-RC-KeycloakName}* _init_ from link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/src/modules/keycloak/index.ts[Keycloak]. For example:

[source,typescript]
----
import { init as initKeycloak } from './keycloak';
----

[id='{context}-applying-keycloak-init']
[discrete]
== Applying {WFM-RC-KeycloakName} _init_

Apply *{WFM-RC-KeycloakName}* _init_ to the security Middleware to enable *{WFM-RC-KeycloakName}* for route protection.

For more security information, see the link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/src/modules/index.ts[Security Setup].

[id='{context}-enabling-keycloak-route-protection']
[discrete]
== Enabling {WFM-RC-KeycloakName} Route Protection

The following code is an example of how to protect routes:

[source,typescript]
----
// This implementation supports role based authentication
app.use('/test', securityMiddleware.protect(role));
----
