[id='pro-working-with-passportjs-{chapter}']
= Introduction

This section includes:

. xref:pro-configuring-passportjs-{chapter}[Configuring Passport.js]
. xref:pro-implementing-the-userrepository-{chapter}[Implementing the UserRepository]
. xref:pro-modifying-a-strategy-{chapter}[Modifying a Strategy]

= Prerequisites
(?)

= Procedure

[id='pro-configuring-passportjs-{chapter}']
[discrete]
== Configuring Passport.js
As the PassportAuth module is the default security module it is install as part of running the Demo App.
Demo application starts with Passport module enabled by default. It is an out of the box security solution for
Default integration using static json files as user source. To use different source please follow guide bellow.
{WFM-RC-NameShort}. Passport.js is a lightweight solution that offers all the
functionality required to get started.

[id='pro-implementing-the-userrepository-{chapter}']
[discrete]
== Implementing the UserRepository

Passport.js requires developers to implement link:++../../../api/{WFM-RC-Api-Version}/auth-passport/docs/interfaces/_src_user_userrepository_.userrepository.html++[UserRepository] that will be used by framework to
fetch user data. UserRepository requires that users data will contain at least username and passwordHash.

For end to end implementation of UserRepository please follow our example app:
link:{WFM-RC-Github-Core}{WFM-RC-Branch}{WFM-RC-PassportAuth-Example}[example]

[id='pro-modifying-a-strategy-{chapter}']
[discrete]
== Modifying a Strategy
The link:++../../../api/{WFM-RC-Api-Version}/auth-passport/docs/modules/_src_auth_defaultstrategy_.html++[default strategy] for the PassportAuth
module implements the Passport.js local strategy. As a developer you may wish
use a different security strategy with the passport.js implementation. You can override the
link:++../../../api/{WFM-RC-Api-Version}/auth-passport/docs/classes/_src_auth_passportauth_.passportauth.html#setup++[PassportAuth.setup] method to
implement any strategy supported by Passport.js.
