[id='{context}-pro-keycloak-enablement']
= Enabling {Keycloak}

IMPORTANT: Enabling *{Keycloak}* requires the disabling of *PassportAuth*.

[discrete]
== Prerequisites

. Ensure you have completed xref:getting-started[Getting Started]
. Docker (tested with version: {WFM-RC-DockerVersion})
. Knowledge of {Keycloak} terminologies. See xref:{context}-understanding-keycloak-terminologies[Understanding {Keycloak} Terminologies] section for more information.

NOTE: If you choose to run your own {Keycloak} instance, ensure that a realm is setup for {PROJECT_NAME} applications
to use. There are two options to setup the realm: import the existing demo link:{WFM-RC-KeycloakDockerURL}{WFM-RC-Branch}/data_files/raincatcher-realm.json[{PROJECT_NAME} realm settings]
(see xref:{context}-import-keycloak-realm-settings[Importing the {Keycloak} Realm Settings] section for more information)
or create your own realm that can be used with the {PROJECT_NAME} applications (see xref:{context}-create-own-keycloak-realm[Creating Your own {Keycloak} Realm] section for more information).

[id='{context}-run-keycloak-docker-image']
[discrete]
== Running the {Keycloak} Docker Image

. Open a terminal and run the *{Keycloak}* Docker image

[source,bash]
----
docker run -p 8080:8080 feedhenry/raincatcher-keycloak
----

For more information about the *{Keycloak}* Docker Image, see the *{Keycloak}* link:{WFM-RC-KeycloakDockerURL}{WFM-RC-Branch}/README.md[README.md].

IMPORTANT: The {Keycloak} realm setup included in this docker image is for demo purposes only. Ensure that you provide proper client 
configurations for production environments. For more information about client configurations, see the {Keycloak} link:{WFM-RC-KeycloakURL}server_admin/topics/clients.html[clients documentation]

[id='{context}-import-keycloak-realm-settings']
[discrete]
== Importing the {Keycloak} Realm Settings

NOTE: This step should only be done if you choose to run your own {Keycloak} instance. The {Keycloak} Docker image
comes with a demo RainCatcher realm setup therefore it does not need to be manually imported.

. Download the link:{WFM-RC-KeycloakDockerURL}{WFM-RC-Branch}/data_files/raincatcher-realm.json[{PROJECT_NAME} realm settings]
. Login to the {Keycloak} admin console. See xref:{context}-accessing-the-keycloak-admin-console[Accessing the {Keycloak} Admin Console] for more information.
. Click 'Add Realm'
. Import the link:{WFM-RC-KeycloakDockerURL}{WFM-RC-Branch}/data_files/raincatcher-realm.json[{PROJECT_NAME} realm settings] you downloaded
. Click 'Create'

This will create the demo RainCatcher realm which includes the setup for three different clients: raincatcher-portal, raincatcher-mobile and raincatcher-cloud.

IMPORTANT: The provided link:{WFM-RC-KeycloakDockerURL}{WFM-RC-Branch}/data_files/raincatcher-realm.json[{PROJECT_NAME} realm settings] is only used for
demo purposes. Ensure that you provide proper client configurations for production environments. For more information 
about client configurations, see the {Keycloak} link:{WFM-RC-KeycloakURL}server_admin/topics/clients.html[clients documentation]

[id='{context}-create-own-keycloak-realm']
[discrete]
== Creating your own {Keycloak} Realm
IMPORTANT: Ensure that you have a deep understanding of {Keycloak}, Node.js and Javascript Adapters before attempting to change any of the configurations below.

NOTE: This step should only be done if you choose to create your own {Keycloak} realm instead of using the existing demo
link:{WFM-RC-KeycloakDockerURL}{WFM-RC-Branch}/data_files/raincatcher-realm.json[{PROJECT_NAME} realm settings].

See the {Keycloak} link:{WFM-RC-KeycloakURL}server_admin/topics/realms/create.html[realm] documentation for more information on how to
create a new realm within a {Keycloak} instance.

The realm must adhere to the following configurations in order to use it with the {PROJECT_NAME} applications

* Realm settings
+
----
Required SSL: external
----

* Client settings
** The realm must have three different clients for each of the {PROJECT_NAME} applications: Server, Portal and Mobile.
** Server Client: 
+
----
Enabled: true
Client Protocol: openid-connect
Access Type: bearer-only
Roles: admin, user
----

** Portal Client: 
+
----
Enabled: true
Client Protocol: openid-connect
Access Type: public
Standard Flow Enabled: true
Valid Redirect URIs: * [Ensure that this is configured with the correct URL patterns in production environments]
Web Origins: *
roles: admin
----

** Mobile Client:
+
----
Enabled: true
Client Protocol: openid-connect
Access Type: public
Standard Flow Enabled: true
Valid Redirect URIs: * [Ensure that this is configured with the correct URL patterns in production environments]
Web Origins: *
roles: user
----

** For more information on the configurations above, see the {Keycloak} link:{WFM-RC-KeycloakURL}server_admin/topics/clients/client-oidc.html[OpenID Connect configurations] documentation.

* User settings
** Ensure that each users has the following attribute fields:
*** id: Used as an identifier for the user.
*** avatar: A link to the user's avatar image to be displayed on the user panel (Used in the mobile application). 
*** name: The name of the user to be displayed on the user panel (Used in the mobile application).
** For more information on user attributes, see the {Keycloak} link:{WFM-RC-KeycloakURL}server_admin/topics/users/attributes.html[user attributes] documentation.
** Ensure that each users has the appropriate client roles. For more information on setting roles, see {Keycloak}
link:{WFM-RC-KeycloakURL}server_admin/topics/roles/user-role-mappings.html[user role mapping] documentation.

[id={context}-adding-keycloak-configuration]
[discrete]
== Adding {Keycloak} Configuration

[id={context}-adding-keycloak-configuration-server]
[discrete]
=== Adding Keycloak Configuration in the Server Application
. Choose which _configuration file_ to edit:
+
.*{Keycloak}* Configuration File
|===
|Area |File Name | File Location

|Development
|link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/config-dev.js[config-dev.js]
|/demo/server/config-dev.js

|Production
|link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/config-prod.js[config-prod.js]
|/demo/server/config-prod.js

|===
+
. Open the configuration file and fill in the missing field values for realm, auth-server-url and resource:
+
[source,javascript]
----
"keycloakConfig":{
                    "realm": "raincatcher",
                    "bearer-only": true,
                    "auth-server-url": "http://localhost:8080/auth",
                    "ssl-required": "external",
                    "resource": "raincatcher-cloud",
                    "use-resource-role-mappings": true
                  }
----
NOTE: Ensure that the realm, auth-server-url and resource values corresponds to your client configuration within your 
realm. Ensure that the values for the fields bearer-only, ssl-required and use-resource-role-mappings are not changed.
For more information, see the {Keycloak} link:{WFM-RC-KeycloakURL}securing_apps/topics/oidc/nodejs-adapter.html[Node.js Adapter documentation].

IMPORTANT: Filling in the realm, auth-server-url and resource fields in the keycloakConfig also enables {Keycloak} in the server application

[discrete]
=== Keycloak Configuration in the Mobile Application
The _Keycloak Configuration_ for the mobile application is already filled in. This may be customized by changing the realm, url and clientId fields
within the application's link:{WFM-RC-AngularJsURL}{WFM-RC-Branch}/demo/mobile/src/config.json[config.json] to values which corresponds to your own client configuration.

NOTE: Ensure that the values for the rest of the fields apart from the realm, url and clientId are not changed.

For more information on Javascript Adapter configurations,
see the {Keycloak} link:{WFM-RC-KeycloakURL}securing_apps/topics/oidc/javascript-adapter.html[Javascript Adapter] documentation.

[discrete]
=== Keycloak Configuration in the Portal Application
The _Keycloak Configuration_ for the portal application is already filled in. This may be customized by changing the realm, url and clientId fields
within the application's link:{WFM-RC-AngularJsURL}{WFM-RC-Branch}/demo/portal/src/config.json[config.json] to values which corresponds to your own client configuration.

NOTE: Ensure that the values for the rest of the fields apart from the realm, url and clientId are not changed.

For more information on Javascript Adapter configurations,
see the {Keycloak} link:{WFM-RC-KeycloakURL}securing_apps/topics/oidc/javascript-adapter.html[Javascript Adapter] documentation.

[id={context}-enabling-keycloak-on-the-server]
[discrete]
== Enabling {Keycloak} on the {PROJECT_NAME} Applications

[discrete]
=== Enabling {Keycloak} on the Server Application
. Fill in the Keycloak configuration in the server application.
. At this point, the routes are protected by {Keycloak}.

See xref:{context}-adding-keycloak-configuration-server[Adding Keycloak Configuration in the Server] for more information.

[discrete]
=== Enabling {Keycloak} on the Mobile Application
. Open the file link:{WFM-RC-AngularJsURL}{WFM-RC-Branch}/demo/mobile/src/app/app.js[app.js] in location _/demo/mobile/src/app/_ and change the contents to:

[source,javascript]
----
    // Enables passport auth service to be used
    // require('./passport'),
    // require('@raincatcher/angularjs-auth')(),
    // Enables keycloak auth service to be used
    require('./keycloak'),
----


NOTE: Ensure that Passport.js is disabled by not requiring ./passport and @raincatcher/angularjs-auth module.

[discrete]
=== Enabling {Keycloak} on the Portal Application
. Open the file link:{WFM-RC-AngularJsURL}{WFM-RC-Branch}/demo/portal/src/app/main.js[main.js] in location _/demo/portal/src/app/_ and change the contents to:

[source,javascript]
----
  // Enables passport auth service to be used
  // require('./passport'),
  // Enables keycloak auth service to be used
  require('./keycloak'),
----

NOTE: Ensure that Passport.js is disabled by not requiring ./passport.

[id={context}-accessing-the-keycloak-admin-console]
[discrete]
== Accessing the {Keycloak} Admin Console

. To access the _{Keycloak} Admin Console_, navigate to _http://localhost:8080/auth/_
+
See xref:{context}-credentials-for-the-demo-application[Credentials for the Admin Console] section
to see the credentials used by the Keycloak docker image.

For more information about the admin console, see {Keycloak} link:{WFM-RC-KeycloakURL}server_admin/topics/admin-console.html[admin console] documentation