[id='{context}-pro-keycloak-implementation']
= Implementing {Keycloak}

[discrete]
== Prerequisites

. Ensure you have completed xref:getting-started[Getting Started]
. A {Keycloak} server

== Using {Keycloak} to secure Express endpoints
NOTE: The demo server uses the {Keycloak} Node.js Adapter. For more information, see the
link:{WFM-RC-KeycloakURL}securing_apps/topics/oidc/nodejs-adapter.html[Node.js Adapter documentation].

[id='{context}-implement-endpointsecurity-interface']
[discrete]
== Implement the EndpointSecurity Interface

. Import the link:{WFM-RC-CoreURL}{WFM-RC-Branch}/cloud/auth/src/EndpointSecurity.ts[EndpointSecurity Interface].
+
[source,typescript]
----
import { EndpointSecurity } from '@raincatcher/express-auth';
----
+
. Implement the EndpointSecurity interface
+
See the sample link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/src/modules/keycloak/index.ts[Keycloak implementation] of
the EndpointSecurity interface as a reference on how this can be implemented.

[id='{context}-enable-keycloak-security-middleware']
[discrete]
== Enable {Keycloak} Security Middleware for Route Protection
. Instantiate {Keycloak} and install the {Keycloak} middleware to your express app.
+
This is implemented in the link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/src/modules/keycloak/index.ts[Keycloak implementation]
within the init function. 

+
. Apply this init which returns the {Keycloak} security middleware to be used for protecting express routes.

+
[source,typescript]
----
import { init as initKeycloak } from './keycloak';
...
const securityMiddleware = initKeycloak(app);
----

+
See the link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/src/modules/index.ts[security setup] as a reference on how this can be applied.

For more information on how to setup the {Keycloak} Node.js Adapter, see the link:{WFM-RC-KeycloakURL}securing_apps/topics/oidc/nodejs-adapter.html[Node.js Adapter documentation].


[id='{context}-protect-express-routes']
[discrete]
== Protect Express Routes

The following code is an example of how to protect routes:

[source,typescript]
----
// This implementation supports role based authentication
app.use('/test', securityMiddleware.protect(role));
----

See the link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/src/modules/index.ts[security setup] as a reference on how routes can be protected.

For more information on protecting express routes, see the link:{WFM-RC-KeycloakURL}securing_apps/topics/oidc/nodejs-adapter.html[Node.js Adapter documentation].
