[id='ref-passportjs-securitystrategy-{chapter}']
= Defining the Security Strategy for {WFM-RC-NameShort} Passport.js

This section includes:

. xref:understanding-session-management-{chapter}[Understanding Session Management]
. xref:defining-access-control-{chapter}[Defining Access Control]
. xref:defining-password-storage-{chapter}[Defining Password Storage]
. xref:passportjs-authentication-{chapter}[Passport.js Authentication]
. xref:passportjs-authorization-{chapter}[Passport.js Authorization]

[id='understanding-session-management-{chapter}']
== Understanding Session Management

The _express-session_ module provides session management functionality for *Passport.js*.
For more information, see link:https://github.com/expressjs/session[express-session].

[id='defining-access-control-{chapter}']
== Defining Access Control
*Passport.js* provides role based access control and _routes_ are protected by these roles.
_authService_ is an an implementation of link:++../../../api/{WFM-RC-Api-Version}/auth-passport/docs/classes/_src_auth_passportauth_.passportauth.html++[Passport.js].
For more information, see the following code snippet:

[source,typescript]
----
app.get('/testAdminEndpoint', authService.protect('admin'), (req: express.Request, res: express.Response) => {
  res.json({ routeName: '/testAdminEndpoint', msg: 'authorized to access admin endpoint' });
});
----

NOTE: Demo roles are defined as an array in link:https://github.com/feedhenry-raincatcher/raincatcher-core/blob/{WFM-RC-Branch}/demo/data/src/users.json[user.json].

[id='defining-password-storage-{chapter}']
== Defining Password Storage
The link:++../../../api/{WFM-RC-Api-Version}/auth-passport/docs/interfaces/_src_user_userrepository_.userrepository.html#getuserbylogin++[User Repository Interface] is used to store *Passport.js* user data.
To point *Passport.js* to a datasource, you must implement the User Repository Interface.

[id='passportjs-authentication-{chapter}']
== Passport.js Authentication
{WFM-RC-NameShort} uses the Default Strategy for username/password authentication, and authentication happens on the cloud server.
The *Passport.js* authentication service uses a default custom strategy that is based on the local *Passport.js* strategy.
The *Passport.js* local strategy is database agnostic.

*Passport.js* uses link:../../../raincatcher-docs/{WFM-RC-Api-Version}{WFM-RC-Api-Endpoint-Security}#authenticate[authenticate] middleware for accepting user credentials and creates a session entry for a user.
To access _express_ routes, a user must login using their credentials. A cookie containing a user session key is used to authenticate and authorize a user who is requesting a server endpoint.

NOTE: For demonstration purposes, the login post route has an authenticate method that checks the _userId_ and _password_
against the stored _user.json_ file. It also checks the user's role against the role on _user.json_.

For more information, see the link:{WFM-RC-Github-Core}{WFM-RC-Branch}{WFM-RC-PassportAuth-Example}[Passport.js example].

[id='passportjs-authorization-{chapter}']
== Passport.js Authorization
Authorization is supported by link:++../../../api/{WFM-RC-Api-Version}/auth-passport/docs/interfaces/_src_auth_passportauth_.endpointsecurity.html#protect++[protect middleware] that validates a _user session id_ against session.
