
[id='{context}-ref-mobile']
= {PROJECT_NAME} Mobile application

Mobile angular.js based application that provides interface for field operators.
Developers who base their solution on {PROJECT_NAME} can extend it by providing additional UI elements, themes and functionalities.

== Local development

Installation

    npm install

== Running on a browser

After installing all dependencies, run these commands to test this application on a local browser:

`npm start`

or

`grunt serve:local --url=http://localhost:8001`

The `url` parameter should be the root of the API server application running the api endpoints. See xref::{context}-ref-server[server side documenation] for information how to run server

== Repository structure

===== src/app
Main folder containing the logic for the application. The app is mainly concerned in providing the setup and configuration values for the {PROJECT_NAME} and angularjs modules that are used by it.

===== `src/app/services`
Contains AngularJS services that are utilized by the {PROJECT_NAME} modules to retrieve data. The app has the opportunity to provide an implementation that utilizes any technology for data retrieval, including static fixtures for testing.

===== `src/app/app.js`
Has a small AngularJS controller for displaying a template before data is loaded from the backend server.

===== `src/sass`
Contains app-wide [Sass](http://sass-lang.com/) files that are compiled by the build pipeline.

===== `src/app/initialization`
Contains configuration values and initial bootstrapping code for the angularjs application.

===== `src/res`
Contains resource files (mostly bitmaps) that are used by the UI. These are also included in the various resolutions expected by the native apps.

===== `www/`
Generated directory containing the output files of the local build process.
This directory's contents are what is served by the local development web server.

== Running on a device emulator

To run this application on a device emulator, setup the appropriate native SDKs and run the app through the following commands:

1. Change config.xml content field to point to runing application server
   Provide valid url value.

`<content src="index.html?url=http://localhost:8001" />`

2. Build Android

`cordova prepare`
`cordova build android --verbose`

3) Push apk to your device

`cordova run android`

See the [Apache Cordova project documentation](https://cordova.apache.org/docs/) for details on how to configure your environment for running applications on a device emulator.
