[id='{context}-ref-passportauth-securitystrategy']
= Defining the Security Strategy for {WFM-RC-NameShort} PassportAuth

This section includes:

. xref:{context}-understanding-passportauth-session-management[Understanding PassportAuth Session Management]
. xref:{context}-defining-passportauth-access-control[Defining PassportAuth Access Control]
. xref:{context}-defining-passportauth-password-storage[Defining PassportAuth Password Storage]
. xref:{context}-passportauth-authentication[PassportAuth Authentication]
. xref:{context}-passportauth-authorization[PassportAuth Authorization]
. xref:{context}-customizing-a-strategy[Customizing a Strategy]
. xref:{context}-passportAuth-demo-users-and-access-roles[PassportAuth Demo Users and Access Roles]

[id='{context}-understanding-passportauth-session-management']
== Understanding PassportAuth Session Management

The _express-session_ module provides session management functionality for *PassportAuth*.
For more information, see link:https://github.com/expressjs/session[express-session].

[id='{context}-defining-passportauth-access-control']
== Defining PassportAuth Access Control
_Routes_ are protected by *PassportAuth* which provides role based access control.
_AuthService_ is an an implementation of link:../../../raincatcher-docs/{WFM-RC-Api-Version}{WFM-RC-Api-Passport-Auth}[PassportAuth].
For more information, see the following example:

[source,typescript]
----
app.get('/testAdminEndpoint', authService.protect('admin'), (req: express.Request, res: express.Response) => {
  res.json({ routeName: '/testAdminEndpoint', msg: 'authorized to access admin endpoint' });
});
----

NOTE: Demo roles are defined in link:{WFM-RC-CoreURL}{WFM-RC-Branch}/demo/server/src/modules/wfm-user/users.json[user.json].

[id='{context}-defining-passportauth-password-storage']
== Defining PassportAuth Password Storage
The *PassportAuth* user data is stored in link:../../../api/{WFM-RC-Api-Version}{WFM-RC-Api-User-Repository}#getuserbylogin[User Repository Interface].
Make sure that the _User Repository Interface_ is implemented in order to point *PassportAuth* to a datasource.

[id='{context}-passportauth-authentication']
== PassportAuth Authentication
{WFM-RC-NameShort} authentication is handled by the cloud server using users unique username and password combination.
The *PassportAuth* service is a default authentication strategy as based on the local *Passport.js* implementation.

*PassportAuth* uses link:../../../api/{WFM-RC-Api-Version}{WFM-RC-Api-Endpoint-Security}#authenticate[authenticate]
middleware for cookie based authentication.To access _express_ routes,
a user must login using their credentials. A cookie containing a user session key is used to authenticate and
authorize a user who is requesting a server endpoint.

NOTE: In the demonstration application, the login post route has an authenticate() method that checks user credentials
against the stored credentials in the _user.json_ file. It also checks the user's role against the role on _user.json_.

For more information, see the link:{WFM-RC-Github-Core}{WFM-RC-Branch}{WFM-RC-PassportAuth-Example}[PassportAuth example].

[id='{context}-passportauth-authorization']
== PassportAuth Authorization
Authorization is supported by link:../../../api/{WFM-RC-Api-Version}{WFM-RC-Api-Endpoint-Security}[protect middleware] that validates a _user session id_ against session.

[id='{context}-customizing-a-strategy']
== Customizing a Strategy
The link:default strategy for the *PassportAuth* module implements the *Passport.js* local strategy.
To use a different security strategy that is supported by {WFM-RC-NameShort}, override the
link:../../../api/{WFM-RC-Api-Version}{WFM-RC-Api-Passport-Auth}[PassportAuth.setup] method.

[id='{context}-passportAuth-demo-users-and-access-roles']
== PassportAuth Demo Users and Access Roles
*PassportAuth* is by default integrated with the Demo application and contains sample users and access roles which are defined in the link:https://github.com/feedhenry-raincatcher/raincatcher-core/blob/{WFM-RC-Branch}/demo/server/src/modules/wfm-user/users.json[Demo Data] JSON file.
