[id='{context}-ref-server']
= {PROJECT_NAME} Server application

Server node.js application that provides api for mobile and portal clients.
Developers who base their solution on {PROJECT_NAME} can extend it by providing additional API and using custom plugins.

Application has modular structure - all functionalities and integrations are brought in as modules which can be removed or replaced when not needed.

== {PROJECT_NAME} Server

1. Active release

This version contains all resources including javascript and other build artifacts https://github.com/feedhenry-{PROJECT_NAME}/{PROJECT_NAME}-server

master version always contains the most recent release.

> Note: You can also reference to specific relase version by using tag.

2. Active development version

This version is used by {PROJECT_NAME} contributors and contains only TypeScript source code. https://github.com/feedhenry-{PROJECT_NAME}/{PROJECT_NAME}-core/blob/master/demo/server

== Server side application development guide

Cloud application can be launched using

    npm run start

For debugging use

    npm run startDebug

> Note: Both commands will use tool called `ts-node` that will run process without compiling typescript source code.

If you wish to run your code using node.js directly it's needs to be compiled first

    npm run build
    node src/index.js

When compiling your source code ts-node command will use compiled javascript files
To clean compiled javascript files use:

    npm run clean

=== Prerequisites for local environment

- mongodb installed and running on port 27017
URL controlled by `process.env.MONGO_CONNECTION_URL` and `config-{env}.json` file.
- redis installed and running on port 6379
URL controlled by `process.env.REDIS_CONNECTION_URL` and `config-{env}.json` file.

> Note: If you running {PROJECT_NAME} solution as part of RHMAP platform this requirements will be satisfied automatically and you do not need change any values in configuration.

=== Server side configuration

Server application offers different configuration profiles depending on target application deployment.

- config-dev.js (for developer/local setup - used by default)
- config-prod.js (for production uses)

You can also add another profile names using `config-profile-name.js` pattern.

Profiles can be changed using `process.env.CONFIG_PROFILE` variable.
For example:
```
// use production profile.
process.env.CONFIG_PROFILE === 'prod'
// it will load config-prod.js file in top level application
```

By default server will load development profile.

All configuration parameters are documented directly in javascript file.
Developers building their solution on top of the {PROJECT_NAME} are free to extend configuration for their own needs.

=== Structure

 `modules` - folder contains sample implementation for {PROJECT_NAME} integrations like sync, security. Developers are free to modify and tweak them.

 `user-routes` - contains custom routes (non {PROJECT_NAME} specific)

 `app.js` - Main application code that mounts express routes

=== Configuring custom query parameters for mobile clients

Mobile clients based on the sync framework might not require to receive all WorkOrders in order to operate.

To save on local memory usage, data traffic and improve performance, additional filters can be added to limit those.

In this sample implementation, WorkOrders that are in a complete state stop being sent to mobile clients after two days of their completion. This can be configured via the `sync.daysToExcludeCompleteWorkorders` configuration key. It illustrates a way to include a relatively complex MongoDB query filter into the chain that is used by the list handler for the sync framework.
